services:
  db:
    image: mysql:8.0 
    container_name: mysql_db_projakk 
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb
    ports:
      - "4312:3306"
    volumes:
      - db_data_projakk:/var/lib/mysql # 👈 ตั้งชื่อตู้เย็นใบใหม่
    networks:
      - projakk_net
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_projakk 
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306 
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 64M 
    ports:
      - "8833:80" 
    depends_on:
      - db
    networks:
      - projakk_net 
    restart: always

networks:
  projakk_net: 
    driver: bridge

volumes:
  db_data_projakk: # 👈 ประกาศสร้างตู้เย็นใบใหม่ (ชื่อตรงกับข้างบนเป๊ะๆ)